### ISSUE TITLE
similar_index_for_filter issue

### ISSUE THREAD

**Issue by zhl95** [he-y/filter-pruning-geometric-median#11]
Thanks for the excellent work. But I got a problem here.

In "get_filter_similar" method, the mask is generated by: similar_index_for_filter = [filter_large_index[i] for i in similar_small_index].

Elements of similar_small_index and filter_large_index vectors are indices of filters. Why use the index of filters to slice another list (filter_large_index[i])? On the other hand, errors may occur.

Think this way, there are 16 filters. the similar_small_index contains 15, which is one of the smallest simi_sum filters which need to be pruned. But filter_large_index contains 10 elements only and 15 is not included.

**Comment by he-y** [comment]
Please refer to my [reply](https://github.com/he-y/filter-pruning-geometric-median/issues/10#issuecomment-506928415) in the other issue.

Assume there are 16 filters.
1. "filter_large_index" and “filter_small_index” is for norm-based criterion, assume 3 filters selected from 16 filters. Now we have 13 remaining filters.
2. "similar_large_index" and "similar_small_index" is for FPGM criterion, assume 4 filters selected from 13 filters. Now we have 9 remaining filters.

This function ( similar_index_for_filter = [filter_large_index[i] for i in similar_small_index] ) is about mapping the "9 in 13 index"  to "13 in 16 index". Details is shown in the image.

![image](https://user-images.githubusercontent.com/10541284/60511318-fcefee00-9d14-11e9-96c9-87cb83a5f534.png)

**Comment by zhl95** [comment]
> Please refer to my [reply](https://github.com/he-y/filter-pruning-geometric-median/issues/10#issuecomment-506928415) in the other issue.
> 
> Assume there are 16 filters.
> 
> 1. "filter_large_index" and “filter_small_index” is for norm-based criterion, assume 3 filters selected from 16 filters. Now we have 13 remaining filters.
> 2. "similar_large_index" and "similar_small_index" is for FPGM criterion, assume 4 filters selected from 13 filters. Now we have 9 remaining filters.
> 
> This function ( similar_index_for_filter = [filter_large_index[i] for i in similar_small_index] ) is about mapping the "9 in 13 index" to "13 in 16 index". Details is shown in the image.
> 
> ![image](https://user-images.githubusercontent.com/10541284/60511318-fcefee00-9d14-11e9-96c9-87cb83a5f534.png)

Thanks!. Got it. the similar_filter is calculated based on norm filtered weights.
