### ISSUE TITLE
Question about the complexity

### ISSUE THREAD

**Issue by meijieru** [he-y/filter-pruning-geometric-median#12]
Thanks for the nice work first! And I have some question about complexity.

As stated section 3.4 and the codebase, you choose to calculate pairwise distance in equation (6) by `scipy.spatial.distance.cdist`. Suppose we have n filters with dimension d, the complexity here is $n^2 d$. If we explicit compute the geometric median, the complexity is $ nd $ with time for computing geometric median.
The latter seems to be more efficient. So why do you choose equation (6) instead of equation (4)?

Thanks

**Comment by he-y** [comment]
For the first method, we should calculate equation (2) and equation (4).
For the second method, we should calculate equation (6).
We choose the latter one as the complexity of equation (2) is large, as shown in section 3.4.

**Comment by meijieru** [comment]
Yeah, but I think the total cost of equation (2)(4) is less than equation (6).
The latter is O(n^2 * d).
Geometric mean calculation's cost is 
![image](https://user-images.githubusercontent.com/9511136/60753515-61ff4a00-9f88-11e9-86db-9ccc2d42450a.png), which is less than O(n^2 * d).
Once we get the median, the cost for equation (4) is O(n * d).

**Comment by he-y** [comment]
I don't think so. 
d*n^(4/3)*ε^(-8/3) is not less than n^2 * d.
You should consider the value of n, d, and ε together for the complexity of equation (2).

**Comment by meijieru** [comment]
Got it. Thanks.
And have you tried using exact geometric median without approximation?
Currently computing mask is really fast actually.
Will we get better result here?

**Comment by he-y** [comment]
I think we could achieve similar results by using the exact geometric median.

**Comment by meijieru** [comment]
Thanks
