### ISSUE TITLE
Reproduce cifar pretrain in table 1

### ISSUE THREAD

**Issue by meijieru** [he-y/filter-pruning-geometric-median#13]
Could you please share the pretrained cifar models for reproducing the result in table 1?
Thanks for your nice work!

**Comment by he-y** [comment]
Thanks for the question.
The pre-trained models have been already released in [google driver](https://drive.google.com/drive/u/1/folders/1w_Max8L5ICJZSrlha8UybHfICik-iX95). 

Specifically, please find the "baseline_without_pruning" in [this directory](https://drive.google.com/drive/u/1/folders/1YLhcY487U0ZdGiDHzJBJZOJLFYBhrBoD).

**Comment by meijieru** [comment]
Thanks!
Maybe you could refer it in the readme.
By the way, lots of link in readme is broken.

**Comment by he-y** [comment]
Thanks for your suggestion!
I have updated Readme.
