### ISSUE TITLE
About the mathematical notations.

### ISSUE THREAD

**Issue by zeakey** [he-y/filter-pruning-geometric-median#14]
Hi, thanks for open-sourcing the code.

I got confused on some of the mathematical notations.

1. Why did you choose the `geometric mean` ? Is there theoratical evidence that 'points near GM can be represented by others'? Why don't just use the `mean value` of all points, because the `mean value` is exactly the linear combination of all points.

2.  Eq.10 of the paper. 
    
    ![TIM图片20190709202555](https://user-images.githubusercontent.com/6763078/60887863-ed7a2300-a287-11e9-8aa6-6a5803c147f9.png)
    step-1 to step-2 is valid ONLY IF g(x) and ||x - F_{i,j^*}|| share the same minimal point. Is there asumption or proof to guarantee this?

**Comment by zeakey** [comment]
而且我认为等号右边两项的求 min 的取值范围都不一样。第一项是针对 `j!=j^*` 取最小值的，第二项应该是针对所有的 j 取最小值。

**Comment by he-y** [comment]
Thanks for the question.
Please see the correction at [link](https://github.com/he-y/filter-pruning-geometric-median/blob/master/pdf/FPGM_updated.pdf).

**Comment by zeakey** [comment]
Thx for the updating.
