### ISSUE TITLE
Can't find the images in IMAGENET/TRAIN/ folder

### ISSUE THREAD

**Issue by JustinAsdz** [he-y/filter-pruning-geometric-median#17]
I have set the arg data as /data/groceries/imagenet1
and it is supposed to get the training data from the arg above + /train

But the  mistake occured:

RuntimeError: Found 0 files in subfolders of: /data/groceries/imagenet1/train
Supported extensions are: .jpg,.jpeg,.png,.ppm,.bmp,.pgm,.tif

**Comment by he-y** [comment]
Please follow [the process of ImageNet](https://github.com/he-y/filter-pruning-geometric-median#process-of-imagenet-dataset).

**Comment by JustinAsdz** [comment]
Problem solved  ACCORDING to the process of FACEBOOK which is mentioned in the notes of project
Thanks a lot 
(and the link is here)
https://github.com/facebook/fb.resnet.torch/blob/master/INSTALL.md#download-the-imagenet-dataset
