### ISSUE TITLE
geometric median issue

### ISSUE THREAD

**Issue by pikerbright** [he-y/filter-pruning-geometric-median#19]
As issue https://github.com/he-y/filter-pruning-geometric-median/issues/8

The zero filters which is set in mask operation will always be in the first several indexes in weight_vec_after_norm.
So if we use distance.cdist to calculate similar_matrix, the similar_matrix is like this 
0  0  0  0  0.x  0.x  0.x
0  0  0  0  0.x  0.x  0.x
0  0  0  0  0.x  0.x  0.x
0  0  0  0    0   0.x  0.x
0.x  0.x  0.x  0.x  0.x  0  0.x  0.x
the left top matrix values are all zeros.
so these zero filters will always become the geometric-median, because these filters are near the geometric-median point in params space.

And if we train net from scratch, these mask out zeros filters depends on the random weight initialization. Is that correct?
 
Is my understanding right?

**Comment by he-y** [comment]
No.
Please see [this reply](https://github.com/he-y/filter-pruning-geometric-median/issues/10#issuecomment-506928415).
The candidate filters of GM method are the remaining filters after pruning with norm-based criterion.

**Comment by pikerbright** [comment]
@he-y 我还是不太明白。
我举个例子。假如我不用norm-based criterion，只用dist-based criterion 60%，train from scratch。
网络随机初始化。那第一轮的mask操作，会在所有的filter中计算GM，离GM最近的60%的filter被置0。
然后进行一个epoch训练。
在第二轮mask操作中，我们再计算GM时，由于有60%的filter是0，他们互相计算dist时都是0，所以这60%的filter基本上一定会成为这一轮的GM，他们又会被选择mask为0。
所以我看log中，每一轮被mask的indexes都是不变的。

请问我理解的哪里有问题吗？十分感谢！

**Comment by he-y** [comment]
You are right about this.
Please see [this reply](https://github.com/he-y/filter-pruning-geometric-median/issues/9#issuecomment-504809258) to understand why we do not change the index.

**Comment by pikerbright** [comment]
@he-y 因为网络采用随机normal初始化，所以filter的值应该是正态分布，大多数的filter应该集中在0附近。那第一轮计算出来的GM，应该就是那些分布在0附近的filter，也就是说第一轮的mask操作会把离0较近的filter置为0。然后后面每一轮mask的indexes都一样。
那我可以理解为GM prune对于train from scratch的话，其实也是去掉了norm较小的filter吗？
但是对于pretrain的prune，GM prune是去掉了那些离GM近，可以被其他filter取代的filter？

十分感谢！

**Comment by he-y** [comment]
If you only consider the scratch model, all the filters are near to zero.
In this situation, **ANY** pruning criterion would lead to "the removal of **small norm** filter", because those filters are what the network has now.

I believe GM and norm-based criterion are still different in this situation, as the norm-based criterion choose the filter with **smallest** norm.

**Comment by pickittwice** [comment]
Hi he, is it rational to remove the pruned(zero) filters from the candidates of distance calculation? as in the dist-only setting, GM seems to keep pruning the pruned filters.

**Comment by he-y** [comment]
@pikerbright 
You are right. Please refer to [this reply](https://github.com/he-y/filter-pruning-geometric-median/issues/9#issuecomment-504809258).

**Comment by colorjam** [comment]
> 在第二轮mask操作中，我们再计算GM时，由于有60%的filter是0，他们互相计算dist时都是0，所以这60%的filter基本上一定会成为这一轮的GM，他们又会被选择mask为0。

@he-y 请问当第一轮操作，把60%的filters至为0以后，在第二轮中，重新计算filters间距离时，假如有5%的filters和前一轮操作的filters不一样，那么实际上是有65%的filters被mask掉？

**Comment by he-y** [comment]
@colorjam 
No. We prune 60% filters during all the training epochs.
We select 60% filters which is nearest to GM.
