### ISSUE TITLE
Tried to allocate one gpu but the commond does work

### ISSUE THREAD

**Issue by JustinAsdz** [he-y/filter-pruning-geometric-median#20]
Nomatter which one I reffered to BY USING 
1.`CUDA_VISIBLE_DEVICES= # `    in the shell line
or
2. `os.environ["CUDA_VISIBLE_DEVICES"] = "#"`  in the py file
it returns the error below
`RuntimeError: CUDA out of memory. Tried to allocate 392.00 MiB (GPU 0; 11.90 GiB total capacity; 11.34 GiB already allocated; 18.94 MiB free; 579.50 KiB cached)`

(the GPU0 is used)

**Comment by he-y** [comment]
We use 
`(commander1)& 
(commander2)&` 
to run commanders concurrently.
If the GPU memory is not enough, please run them separately.

**Comment by JustinAsdz** [comment]
> We use
> `(commander1)& (commander2)&`
> to run commanders concurrently.
> If the GPU memory is not enough, please run them separately.

But I can't run even if all Gpus are available  and totally empty. And the same mistake infomation occurs.
Under only one train command 
'python original_train.py -a resnet50 --save_dir ./snapshots/resnet50-baseline  /data/lianbokai/groceries/imagenet1/  --workers 36'

It can reach the training step and failed there.
![image](https://user-images.githubusercontent.com/38929721/61617445-46d94d80-ac9d-11e9-93a3-b882f3cac8f8.png)

**Comment by he-y** [comment]
How about reducing the batch size?
And what is the version of pytorch?

**Comment by JustinAsdz** [comment]
After setting the batch size to 128 or lower   
The program can run regularly 

And surprisingly, after it can run for the first time. it can be allocated by the code which didn't work at all before.  Either by one or multiple gpu(s).
