### ISSUE TITLE
pruning vgg issue

### ISSUE THREAD

**Issue by yyx1107** [he-y/filter-pruning-geometric-median#21]
Hi! I want to prune the vggnet model.But I found that pruning_cifar_vgg.py didn't use the 'do_grad_mask' function.
Is there any difference between resnet and vgg?
Hope for your reply~

**Comment by he-y** [comment]
We do not explicitly choose the function for different structures. We just want to show that our method works for different settings.
Maybe you can try to find out the correlation between structures and gradients, and this is interesting.

**Comment by yyx1107** [comment]
Got it!Thank you ~

**Comment by yyx1107** [comment]
@he-y Sorry to bother you.When I add the function to the pruning process, I got an error.
Traceback (most recent call last):
  File "pruning_cifar_vgg.py", line 454, in <module>
    main()
  File "pruning_cifar_vgg.py", line 181, in main
    m.do_grad_mask()
  File "pruning_cifar_vgg.py", line 435, in do_grad_mask
    a = item.grad.data.view(self.model_length[index])
AttributeError: 'NoneType' object has no attribute 'data'

**Comment by he-y** [comment]
@yyx1107 
Please take a look at [this link](https://discuss.pytorch.org/t/problem-on-variable-grad-data/957/14).
