### ISSUE TITLE
residual network pruning

### ISSUE THREAD

**Issue by Yuting-Gao** [he-y/filter-pruning-geometric-median#23]
Hi, I wonder how you handle the residual structure in the residual network, such as resnet20.
In your pruning code https://github.com/he-y/soft-filter-pruning/blob/master/utils/get_small_model.py, line 380, you write "# just conv1 of block, the input dimension should not change for shortcut",  so it means you don't pruned the last conv in the resblock?

**Comment by he-y** [comment]
Please take a look at the dimension of the original and pruned model (Part of ResNet-50).

name of layer: conv1.weight
	 *** small model torch.Size([45, 3, 7, 7])
	 *** big model torch.Size([64, 3, 7, 7])
name of layer: bn1.weight
	 *** small model torch.Size([45])
	 *** big model torch.Size([64])
name of layer: bn1.bias
	 *** small model torch.Size([45])
	 *** big model torch.Size([64])
name of layer: layer1.0.conv1.weight
	 *** small model torch.Size([45, 45, 1, 1])
	 *** big model torch.Size([64, 64, 1, 1])
name of layer: layer1.0.bn1.weight
	 *** small model torch.Size([45])
	 *** big model torch.Size([64])
name of layer: layer1.0.bn1.bias
	 *** small model torch.Size([45])
	 *** big model torch.Size([64])
name of layer: layer1.0.conv2.weight
	 *** small model torch.Size([45, 45, 3, 3])
	 *** big model torch.Size([64, 64, 3, 3])
name of layer: layer1.0.bn2.weight
	 *** small model torch.Size([45])
	 *** big model torch.Size([64])
name of layer: layer1.0.bn2.bias
	 *** small model torch.Size([45])
	 *** big model torch.Size([64])
name of layer: layer1.0.conv3.weight
	 *** small model torch.Size([180, 45, 1, 1])
	 *** big model torch.Size([256, 64, 1, 1])
name of layer: layer1.0.bn3.weight
	 *** small model torch.Size([180])
	 *** big model torch.Size([256])
name of layer: layer1.0.bn3.bias
	 *** small model torch.Size([180])
	 *** big model torch.Size([256])
name of layer: layer1.0.downsample.0.weight
	 *** small model torch.Size([256, 45, 1, 1])
	 *** big model torch.Size([256, 64, 1, 1])
name of layer: layer1.0.downsample.1.weight
	 *** small model torch.Size([256])
	 *** big model torch.Size([256])
name of layer: layer1.0.downsample.1.bias
	 *** small model torch.Size([256])
	 *** big model torch.Size([256])
name of layer: layer1.1.conv1.weight
	 *** small model torch.Size([45, 256, 1, 1])
	 *** big model torch.Size([64, 256, 1, 1])
name of layer: layer1.1.bn1.weight
	 *** small model torch.Size([45])
	 *** big model torch.Size([64])
name of layer: layer1.1.bn1.bias
	 *** small model torch.Size([45])
	 *** big model torch.Size([64])
name of layer: layer1.1.conv2.weight
	 *** small model torch.Size([45, 45, 3, 3])
	 *** big model torch.Size([64, 64, 3, 3])
name of layer: layer1.1.bn2.weight
	 *** small model torch.Size([45])
	 *** big model torch.Size([64])
name of layer: layer1.1.bn2.bias
	 *** small model torch.Size([45])
	 *** big model torch.Size([64])
name of layer: layer1.1.conv3.weight
	 *** small model torch.Size([180, 45, 1, 1])
	 *** big model torch.Size([256, 64, 1, 1])
name of layer: layer1.1.bn3.weight
	 *** small model torch.Size([180])
	 *** big model torch.Size([256])
name of layer: layer1.1.bn3.bias
	 *** small model torch.Size([180])
	 *** big model torch.Size([256])
name of layer: layer1.2.conv1.weight
	 *** small model torch.Size([45, 256, 1, 1])
	 *** big model torch.Size([64, 256, 1, 1])
name of layer: layer1.2.bn1.weight
	 *** small model torch.Size([45])
	 *** big model torch.Size([64])
name of layer: layer1.2.bn1.bias
	 *** small model torch.Size([45])
	 *** big model torch.Size([64])
name of layer: layer1.2.conv2.weight
	 *** small model torch.Size([45, 45, 3, 3])
	 *** big model torch.Size([64, 64, 3, 3])
name of layer: layer1.2.bn2.weight
	 *** small model torch.Size([45])
	 *** big model torch.Size([64])
name of layer: layer1.2.bn2.bias
	 *** small model torch.Size([45])
	 *** big model torch.Size([64])
name of layer: layer1.2.conv3.weight
	 *** small model torch.Size([180, 45, 1, 1])
	 *** big model torch.Size([256, 64, 1, 1])
name of layer: layer1.2.bn3.weight
	 *** small model torch.Size([180])
	 *** big model torch.Size([256])
name of layer: layer1.2.bn3.bias
	 *** small model torch.Size([180])
	 *** big model torch.Size([256])

**Comment by Yuting-Gao** [comment]
Do you have resnet20 model on cifar10？------------------ 原始邮件 ------------------
发件人: "Yang He"<notifications@github.com>
发送时间: 2019年8月5日(星期一) 下午3:23
收件人: "he-y/filter-pruning-geometric-median"<filter-pruning-geometric-median@noreply.github.com>;
抄送: "Yuting-Gao"<664320693@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [he-y/filter-pruning-geometric-median] residual network pruning(#23)



Please take a look at the dimension of the original and pruned model (Part of ResNet-50).
 
name of layer: conv1.weight
 *** small model torch.Size([45, 3, 7, 7])
 *** big model torch.Size([64, 3, 7, 7])
 name of layer: bn1.weight
 *** small model torch.Size([45])
 *** big model torch.Size([64])
 name of layer: bn1.bias
 *** small model torch.Size([45])
 *** big model torch.Size([64])
 name of layer: layer1.0.conv1.weight
 *** small model torch.Size([45, 45, 1, 1])
 *** big model torch.Size([64, 64, 1, 1])
 name of layer: layer1.0.bn1.weight
 *** small model torch.Size([45])
 *** big model torch.Size([64])
 name of layer: layer1.0.bn1.bias
 *** small model torch.Size([45])
 *** big model torch.Size([64])
 name of layer: layer1.0.conv2.weight
 *** small model torch.Size([45, 45, 3, 3])
 *** big model torch.Size([64, 64, 3, 3])
 name of layer: layer1.0.bn2.weight
 *** small model torch.Size([45])
 *** big model torch.Size([64])
 name of layer: layer1.0.bn2.bias
 *** small model torch.Size([45])
 *** big model torch.Size([64])
 name of layer: layer1.0.conv3.weight
 *** small model torch.Size([180, 45, 1, 1])
 *** big model torch.Size([256, 64, 1, 1])
 name of layer: layer1.0.bn3.weight
 *** small model torch.Size([180])
 *** big model torch.Size([256])
 name of layer: layer1.0.bn3.bias
 *** small model torch.Size([180])
 *** big model torch.Size([256])
 name of layer: layer1.0.downsample.0.weight
 *** small model torch.Size([256, 45, 1, 1])
 *** big model torch.Size([256, 64, 1, 1])
 name of layer: layer1.0.downsample.1.weight
 *** small model torch.Size([256])
 *** big model torch.Size([256])
 name of layer: layer1.0.downsample.1.bias
 *** small model torch.Size([256])
 *** big model torch.Size([256])
 name of layer: layer1.1.conv1.weight
 *** small model torch.Size([45, 256, 1, 1])
 *** big model torch.Size([64, 256, 1, 1])
 name of layer: layer1.1.bn1.weight
 *** small model torch.Size([45])
 *** big model torch.Size([64])
 name of layer: layer1.1.bn1.bias
 *** small model torch.Size([45])
 *** big model torch.Size([64])
 name of layer: layer1.1.conv2.weight
 *** small model torch.Size([45, 45, 3, 3])
 *** big model torch.Size([64, 64, 3, 3])
 name of layer: layer1.1.bn2.weight
 *** small model torch.Size([45])
 *** big model torch.Size([64])
 name of layer: layer1.1.bn2.bias
 *** small model torch.Size([45])
 *** big model torch.Size([64])
 name of layer: layer1.1.conv3.weight
 *** small model torch.Size([180, 45, 1, 1])
 *** big model torch.Size([256, 64, 1, 1])
 name of layer: layer1.1.bn3.weight
 *** small model torch.Size([180])
 *** big model torch.Size([256])
 name of layer: layer1.1.bn3.bias
 *** small model torch.Size([180])
 *** big model torch.Size([256])
 name of layer: layer1.2.conv1.weight
 *** small model torch.Size([45, 256, 1, 1])
 *** big model torch.Size([64, 256, 1, 1])
 name of layer: layer1.2.bn1.weight
 *** small model torch.Size([45])
 *** big model torch.Size([64])
 name of layer: layer1.2.bn1.bias
 *** small model torch.Size([45])
 *** big model torch.Size([64])
 name of layer: layer1.2.conv2.weight
 *** small model torch.Size([45, 45, 3, 3])
 *** big model torch.Size([64, 64, 3, 3])
 name of layer: layer1.2.bn2.weight
 *** small model torch.Size([45])
 *** big model torch.Size([64])
 name of layer: layer1.2.bn2.bias
 *** small model torch.Size([45])
 *** big model torch.Size([64])
 name of layer: layer1.2.conv3.weight
 *** small model torch.Size([180, 45, 1, 1])
 *** big model torch.Size([256, 64, 1, 1])
 name of layer: layer1.2.bn3.weight
 *** small model torch.Size([180])
 *** big model torch.Size([256])
 name of layer: layer1.2.bn3.bias
 *** small model torch.Size([180])
 *** big model torch.Size([256])
 
&mdash;

**Comment by he-y** [comment]
Please take a look at [this implementation](https://github.com/Eric-mingjie/rethinking-network-pruning/tree/master/cifar/soft-filter-pruning).

**Comment by Yuting-Gao** [comment]
The results in geometric median use the soft filter pruning strategy, right?

**Comment by he-y** [comment]
The final structures of these two methods are the same.
The differences are the pruning criterion and performance.

**Comment by OblivionStaff** [comment]
> The final structures of these two methods are the same.
> The differences are the pruning criterion and performance.

In filter-pruning-geometric-median method, every block in each layer do pruning individually. I think the pruned blocks should have different output channels. But in the get_small_model.py, the blocks in each layer has the same output channels. This confuse me.

**Comment by pyt1234** [comment]
@he-y I was wondering how did you prune the last conv in the residual block but not prune the downsample conv? how did you make the summation?  For example:

> name of layer: layer1.0.conv3.weight
> *** small model torch.Size([180, 45, 1, 1])
> *** big model torch.Size([256, 64, 1, 1])
> name of layer: layer1.0.bn3.weight
> *** small model torch.Size([180])
> *** big model torch.Size([256])
> name of layer: layer1.0.bn3.bias
> *** small model torch.Size([180])
> *** big model torch.Size([256])
> name of layer: layer1.0.downsample.0.weight
> *** small model torch.Size([256, 45, 1, 1])
> *** big model torch.Size([256, 64, 1, 1])
> name of layer: layer1.0.downsample.1.weight
> *** small model torch.Size([256])
> *** big model torch.Size([256])
> name of layer: layer1.0.downsample.1.bias
> *** small model torch.Size([256])
> *** big model torch.Size([256])

180 vs 256 channels? Also, ref #38
