### ISSUE TITLE
Have you tried this algorithm on MobileNet or ShuffleNet? 

### ISSUE THREAD

**Issue by YongtaoGE** [he-y/filter-pruning-geometric-median#25]

**Comment by he-y** [comment]
The paper does not include the results of MobileNet.
But I have tried MobileNet and the algorithm works on MobileNet (we noticed more performance drop than ResNet).

**Comment by WhXl** [comment]
The performance degradation of this algorithm on MobileNet is not due to the use of deep separable convolution and too few parameters, which makes it unsuitable to prune.

**Comment by EveningLin** [comment]
@WhXl 
Isn't it  ”due to“？

**Comment by gkrisp98** [comment]
Hi, do you have the code for pruning MobileNet?
