### ISSUE TITLE
Problem about ResNet20's accuracy on CIFAR-10?

### ISSUE THREAD

**Issue by favorxin** [he-y/filter-pruning-geometric-median#26]
Sorry, I have some problems with ResNet20's accuracy on CIFAR-10. In two papers that can be found, I find two different accuracies and want to know which one is the final accuracy. 
![1](https://user-images.githubusercontent.com/31987475/63083637-d1029200-bf7b-11e9-8e10-42027eff1660.png)

![2](https://user-images.githubusercontent.com/31987475/63083616-c0521c00-bf7b-11e9-949b-4085b3ec9b2f.png)

**Comment by he-y** [comment]
The first one is correct, the second one has some typo and has been fixed.
There is just a small difference between FPGM-mix and FPGM-only.

**Comment by favorxin** [comment]
Thank you for answering! I am really interested in your soft filter pruning method and FPGM. I will follow your work and cite them. Thanks again!
