### ISSUE TITLE
Channel Pruning should be done in the BN layer after the convolution layer.

### ISSUE THREAD

**Issue by OblivionStaff** [he-y/filter-pruning-geometric-median#27]
The formula of the BN layer is like this:  (x - bn.mean) * bn.weight / sqrt(bn.variance + 1e-5) + bn.bias. after channel pruning in a convolution layer, some channels in x are zeros, but according to the formula, the output of these pruned channels in the following BN layer are not zeros. If you get the pruned model without handling each BN layer, the performance drops significantly.

**Comment by he-y** [comment]
Please refer to [this issue](https://github.com/he-y/filter-pruning-geometric-median/issues/7) to see how we handle the BN layers.
The performance of zero model and nonzero model are the same.

**Comment by OblivionStaff** [comment]
> Please refer to [this issue](https://github.com/he-y/filter-pruning-geometric-median/issues/7) to see how we handle the BN layers.
> The performance of zero model and nonzero model are the same.

But it seams that only the bn3 layer in the bottleneck was handled in the imagenet_reset_small.py. I think that handling each BN layers in that way is inconvenient. Maybe just masking the BN layers during training is easier.

**Comment by he-y** [comment]
Yes, you are right. It is easier to mask the BN layers during training.
Maybe this would have an influence on accuracy.

**Comment by liuwenran** [comment]
@OblivionStaff  why only the bn3 layer in the bottleneck was handled, but the performance of zero model and nonzero model are the same? Other bn layers are not important?
