### ISSUE TITLE
Prune weights and bias together

### ISSUE THREAD

**Issue by ruiwen0615** [he-y/filter-pruning-geometric-median#28]
Hi,

Thanks for your work. I have a question, for a convolution layer which has both weights and bias, should I prune them together? I noticed in your implementation, in conv2d, you always set bias = False. For example, a convolution layer has weights tensor [3, 3, 64, 256] and bias tensor 256, after pruning, I should get something like weight tensor [3, 3, 64, 175] and bias tensor 175?

**Comment by he-y** [comment]
Please see [this reply](https://github.com/he-y/filter-pruning-geometric-median/issues/23#issuecomment-518118162) for the detailed dimension of conv layers.

**Comment by ruiwen0615** [comment]
> Please see [this reply](https://github.com/he-y/filter-pruning-geometric-median/issues/23#issuecomment-518118162) for the detailed dimension of conv layers.

Thanks for your reply. I think my question is: weights and bias should be pruned at the same location? For example, the weights tensor is [12, 3, 3, 3], if I prune the channels {1, 3, 7, 8}, then weights tensor become [8, 3, 3, 3], right? For bias tensor, should I also prune {1, 3, 7, 8} channels?

**Comment by he-y** [comment]
Please take a look at my extended journal paper: [Asymptotic Soft Filter Pruning for Deep Convolutional Neural Networks](https://ieeexplore.ieee.org/document/8816678) section 3.E for details.
