### ISSUE TITLE
Why the inference time of pruning resnet20 model is the same with the time without pruning one? I used Resnet20 with pruning and without pruning, their inference time both cost about 90ms more or less. 

### ISSUE THREAD

**Issue by JoelSeniorLiang** [he-y/filter-pruning-geometric-median#29]

**Comment by he-y** [comment]
Please use the "model without zeros" for real acceleration.
Refer to [this issue](https://github.com/he-y/filter-pruning-geometric-median/issues/7).

**Comment by xizi** [comment]
Hi, He Yang, I used ResNet50 with prunning (prunning rate is 0.4) and get without zeros model to test. I found the infer time of bigmodel (without prunning one)  is 20.28ms and smallmodel (prunning one)  is 21.63ms. Can you help me figure out the problem?
