### ISSUE TITLE
np.abs over consine distance

### ISSUE THREAD

**Issue by lizhenstat** [he-y/filter-pruning-geometric-median#30]
Hi, thanks for your great work. I have one question on distance calculation: 
https://github.com/he-y/filter-pruning-geometric-median/blob/master/pruning_cifar10.py#L528
```python
similar_matrix = 1 - distance.cdist(weight_vec_after_norm, weight_vec_after_norm, 'cosine')
similar_sum = np.sum(np.abs(similar_matrix), axis=0)
```
while the cosine distance in scipy is defined as follow:
![cosine_dist](https://user-images.githubusercontent.com/41462408/64308362-8f3d9800-cfcb-11e9-9a89-8965ea89a0d0.png)
Therefore, the distance between two vectors might be negative, right?
Why here use the **np.abs** over similar_matrix(FPGM distance matrix) on cosine distance?

Thanks

**Comment by he-y** [comment]
The default distance is "l2" distance. "Cos" distance is for ablation study. 
Please take a look at section 4.4 "Influence of Distance Type".

**Comment by lizhenstat** [comment]
@Oh, I got it. 
Therefore the default norm distance for "cosine" is L2-norm, distance is defined as cosine distance. 
The default norm distance for "l1" is L1-norm, distance is defined as euclidean distance.

The **cosine similarity** is defined as:
![cosine-similarity](https://user-images.githubusercontent.com/41462408/64309035-de84c800-cfcd-11e9-92af-aee7d310b64f.png)
The **cosine distance** is defined as: 
![cosine-distance](https://user-images.githubusercontent.com/41462408/64309041-e04e8b80-cfcd-11e9-8037-e5139b4d0364.png)
Therefore the cosine distance is always between [0,2], therefore the similar_matrix should always be positive. 

Thanks
