### ISSUE TITLE
python: can't open file 'pruning_train.py': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by WhXl** [he-y/filter-pruning-geometric-median#32]
请问这个问题如何解决，我想在tensorflow模型上使用你们的方法修建网络，请问代码的核心部分在什么地方?期待你的回复!
How to solve this problem? I want to use your method to build the network in tensorflow model. Where is the core part of the code? I look forward to your reply.

**Comment by he-y** [comment]
The core file is "pruning_imagenet.py".
I have updated readme.
