### ISSUE TITLE
python: can't open file 'main_cifar_vgg_log.py': [Errno 2] No such file or directory 

### ISSUE THREAD

**Issue by jefersonf** [he-y/filter-pruning-geometric-median#33]
I'm trying to run the **Training VGGNet on Cifar-10** example, but I've got the following:
`python: can't open file 'main_cifar_vgg_log.py': [Errno 2] No such file or directory
python: can't open file 'main_cifar_vgg_log.py': [Errno 2] No such file or directory
python: can't open file 'PFEC_vggprune.py': [Errno 2] No such file or directory
python: can't open file 'main_cifar_vgg_log.py': [Errno 2] No such file or directory
python: can't open file 'pruning_cifar_vgg.py': [Errno 2] No such file or directory
python: can't open file 'PFEC_finetune.py': [Errno 2] No such file or directory
python: can't open file 'PFEC_finetune.py': [Errno 2] No such file or directory
python: can't open file 'PFEC_finetune.py': [Errno 2] No such file or directory
python: can't open file 'PFEC_finetune.py': [Errno 2] No such file or directory
python: can't open file 'PFEC_finetune.py': [Errno 2] No such file or directory
python: can't open file 'PFEC_finetune.py': [Errno 2] No such file or directory
python: can't open file 'pruning_cifar_vgg.py': [Errno 2] No such file or directory
python: can't open file 'pruning_cifar_vgg.py': [Errno 2] No such file or directory
python: can't open file 'pruning_cifar_vgg.py': [Errno 2] No such file or directory
python: can't open file 'pruning_cifar_vgg.py': [Errno 2] No such file or directory
python: can't open file 'pruning_cifar_vgg.py': [Errno 2] No such file or directory
python: can't open file 'main_cifar_vgg_log.py': [Errno 2] No such file or directory
python: can't open file 'PFEC_vggprune.py': [Errno 2] No such file or directory
python: can't open file 'main_cifar_vgg_log.py': [Errno 2] No such file or directory`

When I run this:

`~/filter-pruning-geometric-median$ sh VGG_cifar/scripts/PFEC_train_prune.sh`

Could you please help me on this? Am I doing something wrong?

**Comment by he-y** [comment]
Please `cd VGG_cifar` first.

**Comment by jefersonf** [comment]
It doesn't work for me. I think is about permissions or a reference to a file or directory that do not exists, because when I try to run this:

`~/filter-pruning-geometric-median/VGG_cifar$ sh scripts/PFEC_train_prune.sh`

It outputs:
`Traceback (most recent call last):
  File "PFEC_vggprune.py", line 9, in <module>
    sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
NameError: name 'sys' is not defined
save path : ./logs/baseline/main_2
{'arch': 'vgg', 'batch_size': 64, 'cuda': True, 'data_path': './data/cifar.python', 'dataset': 'cifar10', 'depth': 16, 'epochs': 160, 'log_interval': 100, 'lr': 0.1, 'momentum': 0.9, 'no_cuda': False, 'resume': '', 'save_path': './logs/baseline/main_2', 'seed': 1, 'start_epoch': 0, 'test_batch_size': 256, 'train_scratch': '', 'use_scratch': False, 'weight_decay': 0.0001}
Random Seed: 1
python version : 3.6.8 (default, Aug 20 2019, 17:12:48)  [GCC 8.3.0]
torch  version : 0.3.1
cudnn  version : 7005
save path : ./logs/baseline/main_1
{'arch': 'vgg', 'batch_size': 64, 'cuda': True, 'data_path': './data/cifar.python', 'dataset': 'cifar10', 'depth': 16, 'epochs': 160, 'log_interval': 100, 'lr': 0.1, 'momentum': 0.9, 'no_cuda': False, 'resume': '', 'save_path': './logs/baseline/main_1', 'seed': 1, 'start_epoch': 0, 'test_batch_size': 256, 'train_scratch': '', 'use_scratch': False, 'weight_decay': 0.0001}
Random Seed: 1
python version : 3.6.8 (default, Aug 20 2019, 17:12:48)  [GCC 8.3.0]
torch  version : 0.3.1
cudnn  version : 7005
save path : ./logs/baseline/main_3
{'arch': 'vgg', 'batch_size': 64, 'cuda': True, 'data_path': './data/cifar.python', 'dataset': 'cifar10', 'depth': 16, 'epochs': 160, 'log_interval': 100, 'lr': 0.1, 'momentum': 0.9, 'no_cuda': False, 'resume': '', 'save_path': './logs/baseline/main_3', 'seed': 1, 'start_epoch': 0, 'test_batch_size': 256, 'train_scratch': '', 'use_scratch': False, 'weight_decay': 0.0001}
Random Seed: 1
python version : 3.6.8 (default, Aug 20 2019, 17:12:48)  [GCC 8.3.0]
torch  version : 0.3.1
cudnn  version : 7005
Downloading https://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz to ./data/cifar.python/cifar-10-python.tar.gz
Downloading https://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz to ./data/cifar.python/cifar-10-python.tar.gz
Downloading https://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz to ./data/cifar.python/cifar-10-python.tar.gz
0.00B [00:00, ?B/s]Traceback (most recent call last):
  File "PFEC_finetune.py", line 13, in <module>
Traceback (most recent call last):
  File "PFEC_finetune.py", line 13, in <module>
    sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
NameError: name 'sys' is not defined
    sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
NameError: name 'sys' is not defined
Traceback (most recent call last):
  File "PFEC_finetune.py", line 13, in <module>
    sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
NameError: name 'sys' is not defined
Traceback (most recent call last):
  File "PFEC_finetune.py", line 13, in <module>
    sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
NameError: name 'sys' is not defined
Traceback (most recent call last):
  File "PFEC_finetune.py", line 13, in <module>
    sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
NameError: name 'sys' is not defined
Traceback (most recent call last):
  File "PFEC_finetune.py", line 13, in <module>
    sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
NameError: name 'sys' is not defined
Traceback (most recent call last):
  File "pruning_cifar_vgg.py", line 67, in <module>
    os.makedirs(args.save_path)
  File "/home/jeferson/repo/fpenv/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/home/jeferson/repo/fpenv/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/home/jeferson/repo/fpenv/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  [Previous line repeated 2 more times]
  File "/home/jeferson/repo/fpenv/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/home/yahe'
Traceback (most recent call last):
  File "pruning_cifar_vgg.py", line 67, in <module>
    os.makedirs(args.save_path)
  File "/home/jeferson/repo/fpenv/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/home/jeferson/repo/fpenv/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/home/jeferson/repo/fpenv/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  [Previous line repeated 2 more times]
  File "/home/jeferson/repo/fpenv/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/home/yahe'
  0%|                                                          | 8.19k/170M [00:01<1:04:49, 43.8kB/s]Traceback (most recent call last):
  File "pruning_cifar_vgg.py", line 67, in <module>
    os.makedirs(args.save_path)
  File "/home/jeferson/repo/fpenv/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/home/jeferson/repo/fpenv/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/home/jeferson/repo/fpenv/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  [Previous line repeated 2 more times]
  File "/home/jeferson/repo/fpenv/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/home/yahe'
  0%|                                                              | 221k/170M [00:02<27:42, 102kB/s]Traceback (most recent call last):
  File "pruning_cifar_vgg.py", line 67, in <module>
    os.makedirs(args.save_path)
  File "/home/jeferson/repo/fpenv/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/home/jeferson/repo/fpenv/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/home/jeferson/repo/fpenv/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  [Previous line repeated 2 more times]
  File "/home/jeferson/repo/fpenv/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/home/yahe'
  1%|▍                                                            | 1.29M/170M [00:02<10:46, 262kB/s]Traceback (most recent call last):
  File "pruning_cifar_vgg.py", line 67, in <module>
    os.makedirs(args.save_path)
  File "/home/jeferson/repo/fpenv/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/home/jeferson/repo/fpenv/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/home/jeferson/repo/fpenv/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  [Previous line repeated 2 more times]
  File "/home/jeferson/repo/fpenv/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/home/yahe'
  1%|▋                                                            | 1.76M/170M [00:02<06:41, 421kB/s]Traceback (most recent call last):
  File "pruning_cifar_vgg.py", line 67, in <module>
    os.makedirs(args.save_path)
  File "/home/jeferson/repo/fpenv/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/home/jeferson/repo/fpenv/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/home/jeferson/repo/fpenv/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  [Previous line repeated 2 more times]
  File "/home/jeferson/repo/fpenv/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/home/yahe'
  1%|▊                                                            | 2.42M/170M [00:03<04:13, 663kB/s]save path : ./logs/off/scratch/full_model
{'arch': 'vgg', 'batch_size': 64, 'cuda': True, 'data_path': './data/cifar.python', 'dataset': 'cifar10', 'depth': 16, 'epochs': 160, 'log_interval': 100, 'lr': 0.1, 'momentum': 0.9, 'no_cuda': False, 'resume': '', 'save_path': './logs/off/scratch/full_model', 'seed': 1, 'start_epoch': 0, 'test_batch_size': 256, 'train_scratch': '', 'use_scratch': True, 'weight_decay': 0.0001}
Random Seed: 1
python version : 3.6.8 (default, Aug 20 2019, 17:12:48)  [GCC 8.3.0]
torch  version : 0.3.1
cudnn  version : 7005
Downloading https://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz to ./data/cifar.python/cifar-10-python.tar.gz
 92%|███████████████████████████████████████████████████████▉     | 156M/170M [01:46<00:11, 1.19MB/s]=> creating model 'vgg'
Traceback (most recent call last):
  File "main_cifar_vgg_log.py", line 239, in <module>
    main()
  File "main_cifar_vgg_log.py", line 116, in main
    model = models.__dict__[args.arch](dataset=args.dataset, depth=args.depth)
TypeError: 'module' object is not callable
 92%|████████████████████████████████████████████████████████▎    | 157M/170M [01:47<00:10, 1.30MB/s]Traceback (most recent call last):
  File "PFEC_vggprune.py", line 9, in <module>
    sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
NameError: name 'sys' is not defined
 92%|████████████████████████████████████████████████████████▍    | 158M/170M [01:47<00:09, 1.35MB/s]=> creating model 'vgg'
Traceback (most recent call last):
  File "main_cifar_vgg_log.py", line 239, in <module>
    main()
  File "main_cifar_vgg_log.py", line 116, in main
    model = models.__dict__[args.arch](dataset=args.dataset, depth=args.depth)
TypeError: 'module' object is not callable
=> creating model 'vgg'
Traceback (most recent call last):
  File "main_cifar_vgg_log.py", line 239, in <module>
    main()
  File "main_cifar_vgg_log.py", line 116, in main
    model = models.__dict__[args.arch](dataset=args.dataset, depth=args.depth)
TypeError: 'module' object is not callable
 93%|████████████████████████████████████████████████████████▍    | 158M/170M [01:47<00:08, 1.40MB/s]save path : ./logs/PFEC/scratch/train_small_model
{'arch': 'vgg', 'batch_size': 64, 'cuda': True, 'data_path': './data/cifar.python', 'dataset': 'cifar10', 'depth': 16, 'epochs': 160, 'log_interval': 100, 'lr': 0.1, 'momentum': 0.9, 'no_cuda': False, 'resume': '', 'save_path': './logs/PFEC/scratch/train_small_model', 'seed': 1, 'start_epoch': 0, 'test_batch_size': 256, 'train_scratch': './logs/PFEC/scratch/pruned_model/pruned.pth.tar', 'use_scratch': True, 'weight_decay': 0.0001}
Random Seed: 1
python version : 3.6.8 (default, Aug 20 2019, 17:12:48)  [GCC 8.3.0]
torch  version : 0.3.1
cudnn  version : 7005
 93%|████████████████████████████████████████████████████████▌    | 158M/170M [01:48<00:08, 1.48MB/s]Files already downloaded and verified
 93%|████████████████████████████████████████████████████████▊    | 159M/170M [01:48<00:07, 1.62MB/s]=> creating model 'vgg'
Traceback (most recent call last):
  File "main_cifar_vgg_log.py", line 239, in <module>
    main()
  File "main_cifar_vgg_log.py", line 116, in main
    model = models.__dict__[args.arch](dataset=args.dataset, depth=args.depth)
TypeError: 'module' object is not callable
100%|████████████████████████████████████████████████████████████▉| 170M/170M [01:55<00:00, 1.93MB/s]=> creating model 'vgg'
Traceback (most recent call last):
  File "main_cifar_vgg_log.py", line 239, in <module>
    main()
  File "main_cifar_vgg_log.py", line 116, in main
    model = models.__dict__[args.arch](dataset=args.dataset, depth=args.depth)
TypeError: 'module' object is not callable
`

If you take a closer look at the message errors, lots of times the following error appears.
`PermissionError: [Errno 13] Permission denied: '/home/yahe'`

**Comment by he-y** [comment]
Please change the [following lines](https://github.com/he-y/filter-pruning-geometric-median/blob/44030b7befce47b3c59f708dfe546a92c841765d/VGG_cifar/scripts/PFEC_train_prune.sh#L35-L42).
From
 `/home/yahe/compress/filter_similarity/logs/PFEC/finetune160_varience1/`
to
`./logs/PFEC/finetune160_varience1/`

**Comment by jefersonf** [comment]
My env.:

- Python==3.6.8
- PyTorch==0.3.1
- TorchVision==0.3.0

I have to point out three things:

1. When I was setting up the required environment, after install the `torch==0.3.1` it shows that for` torchvision==0.3.0` has requirement `torch>=1.1.0`

2.  Using PyTorch==1.1.0 I've got the error `AttributeError: module 'torch.nn' has no attribute 'ModuleDict'` for the files _`main_cifar_vgg_log.py`_, _`main_cifar_vgg.py`_, _`PFEC_finetune.py`_, _`PFEC_vggprune.py`_, and _`pruning_cifar_vgg.py`_.

```
Traceback (most recent call last):
  File "pruning_cifar_vgg.py", line 11, in <module>
    from torchvision import datasets, transforms
  File "/home/jeferson/repo/fpenv/lib/python3.6/site-packages/torchvision/__init__.py", line 1, in <module>
    from torchvision import models
  File "/home/jeferson/repo/fpenv/lib/python3.6/site-packages/torchvision/models/__init__.py", line 10, in <module>
    from . import segmentation
  File "/home/jeferson/repo/fpenv/lib/python3.6/site-packages/torchvision/models/segmentation/__init__.py", line 1, in <module>
    from .segmentation import *
  File "/home/jeferson/repo/fpenv/lib/python3.6/site-packages/torchvision/models/segmentation/segmentation.py", line 1, in <module>
    from .._utils import IntermediateLayerGetter
  File "/home/jeferson/repo/fpenv/lib/python3.6/site-packages/torchvision/models/_utils.py", line 7, in <module>
    class IntermediateLayerGetter(nn.ModuleDict):
AttributeError: module 'torch.nn' has no attribute 'ModuleDict'

```
3. Using PyTorch==1.2.0 (latest version by now) It seems to start to run but I've got a different error:  `ImportError: libcudart.so.9.0: cannot open shared object file: No such file or directory`  (I use CUDA 10.0, so it could be the version).

**Comment by he-y** [comment]
How about:
`TorchVision==0.2.0  torch==0.3.1`
?

**Comment by jefersonf** [comment]
> How about:
> `TorchVision==0.2.0 torch==0.3.1`
> ?

For this configuration it starts to execute, but it shows some erros like: `NameError: name 'sys' is not defined` and `TypeError: 'module' object is not callable` . The second comes from the import error caused by importing models into the "__ _init_ __.py" file, and running it I got this:

```
Traceback (most recent call last):
  File "__init__.py", line 5, in <module>
    from ..models import *
ValueError: attempted relative import beyond top-level package
```

The complete log for this execution is [here](https://paste.ubuntu.com/p/ykNwBBnFWR/) when running ` ~/filter-pruning-geometric-median/VGG_cifar$ sh scripts/PFEC_train_prune.sh
`

**Comment by he-y** [comment]
This might related to the relative import error.
Please take a look at [this link](https://stackoverflow.com/questions/30669474/beyond-top-level-package-error-in-relative-import).
