### ISSUE TITLE
One question about calculate layer_end and last_index

### ISSUE THREAD

**Issue by cheerss** [he-y/filter-pruning-geometric-median#34]
Thank you for you great work. I have one question about layer end.

As the title say, What layer_end means, how to calculate it? And why last_index is layer_end - 3 when running init_rate in main().

self.mask_index = [x for x in range(0, last_index, 3)], as I think, there is a "3" here because conv2d contains 1 parameter and BN layer contains 2, but you only focus on conv2d layer, so you skip BN's parameters, right? But how about parameters in projection layer? As I understand, you do not consider parameters in projection layer in ResNet, but it seems that you do not skip them here.

Hope for your reply

**Comment by he-y** [comment]
Please see [those lines regarding skip](https://github.com/he-y/filter-pruning-geometric-median/blob/master/pruning_imagenet.py#L598-L613).

**Comment by cheerss** [comment]
Yeah, that's it! How about [pruning_cifar.py](https://github.com/he-y/filter-pruning-geometric-median/blob/master/pruning_cifar10.py#L573-L580)

By the way, I think the layer_end for [resnet20](https://github.com/he-y/filter-pruning-geometric-median/blob/master/scripts/pruning_cifar10_new.sh#L10) should be 54, rather than 52

**Comment by he-y** [comment]
You are right.
[This script about cifar](https://github.com/he-y/filter-pruning-geometric-median/blob/master/scripts/pruning_cifar10.sh#L4-L9) is correct.
For cifar-based resnet, we do NOT use conv as downsample layer, see [this line](https://github.com/he-y/filter-pruning-geometric-median/blob/master/models/resnet.py#L84-L86).

**Comment by cheerss** [comment]
Got it. Thank you for your clear explaination

**Comment by EveningLin** [comment]
@he-y @cheerss 
以resnet18为例，参数计算是3+12+15*3=60 ，我猜因此last_index是60。
第一个问题就是 last_index 难道不是is layer_end +3嘛？
Taking resnet18 as an example, the parameter calculation is 3+12+15 * 3=60, I guess that is why the  last_ The index is 60.
here comes The first question: isn't last_ Is index = layer_ End+3?

第二个点就是为什么卷积是一个参数，bn是两个参数（小白不好意思啦
The second point is why convolution is one parameter and bn is two parameters (new in this area,feeling sorry

第三个点就是为什么注释里面写的是”last index include last fc layer“，如果按照上面的计算是不包含fc层的吧
The third point is why the comment says "last index includes last fc layer". If the above calculation does not include the fc layer

 last index include last fc layer
`            if args.arch == 'resnet18':
                # last index include last fc layer
                last_index = 60# layer_end - 3
                skip_list = [21, 36, 51]`
