### ISSUE TITLE
Question on equivalence of g(x) and g'(x) in FPGM_updated

### ISSUE THREAD

**Issue by lizhenstat** [he-y/filter-pruning-geometric-median#36]
Hi, thanks for your work, I have one question on why you prove the equivalence on g(x) and g'(x), as in equation (5)-(9)
"Note that even if F_{i,j*} is not included in the calculation of the geometric median in Equation(4), 
we could also achieve the same result."

Thanks in advance

**Comment by he-y** [comment]
Please find the [updated version](https://arxiv.org/abs/1811.00250) on arxiv which is more clear on this point.

**Comment by lizhenstat** [comment]
@ Thanks a lot
