### ISSUE TITLE
yolov3的darknet模型

### ISSUE THREAD

**Issue by yyx1107** [he-y/filter-pruning-geometric-median#4]
非常感谢您上一个问题的解答。我还有一个问题想请教您一下。我现在是想用yolov3算法，使用Darknet53模型进行目标识别，想使用您这个压缩算法对得到的模型（数据集是VOC）进行压缩。要怎么进行修改呢，比如训练函数train()或者精度等方面。刚刚接触这一方面，希望您能给一些建议，谢谢~

**Comment by gkrisp98** [comment]
Hi @yyx1107 , have figured out the code for applying FPGM on object detection model ?
