### ISSUE TITLE
the small model of resnet56 for cifar10 performs not as well as the big model ?

### ISSUE THREAD

**Issue by meiniangpp** [he-y/filter-pruning-geometric-median#40]
Hi, I have trained with pruning a resnet56 for cifar10. The big model has accuracy of 89%, while the small model has only 10%. I looked into the details and found there seems to be an error in pruning training. 
When training with pruning, only the first dim of conv weight are masked 0 during filtering. The second dim of conv weight, which matches the input channel number, will not be masked even if some channel of the last conv are masked 0.
However, when transfering to small model, the second dim of conv weight has also to be filtered to keep the shape of input and conv weight match. As a result, some non-zero weights are pruned, and the small model's accuracy drops a lot.
Have you noticed this issue? And how did you solve it ?
Thank you for your patience.
Looking forward to your reply!

**Comment by he-y** [comment]
We have an index alignment operation.
Please see [this reply](https://github.com/he-y/filter-pruning-geometric-median/issues/38#issuecomment-543044443).
