### ISSUE TITLE
small_model.pt accuracy is not equal to big_model.pt

### ISSUE THREAD

**Issue by xizi** [he-y/filter-pruning-geometric-median#41]
Hi, when i train a resnet50 in imagenet, and i use get_small.sh obtain big_model.pt and small_model.pt. the accuracy is equal. but when i train a resnet50 in private dataset, the obtained  small_model.pt accuracy is not equal to big_model.pt. what's the reason about it. the prunning rate is 0.3.

**Comment by xizi** [comment]
Meanwhile, the inference speed of small_model.pt is more slow than the bigger one.

**Comment by he-y** [comment]
For Q1, 
I'm not sure. have you checked the weights of the two models? 
Q2:
As stated in our paper, "Optimization of the addition of ResNet shortcuts and convolutional outputs would also affect the results". This might be the reason.

**Comment by xizi** [comment]
Hi, Can i talk with you in zhihu?

**Comment by xizi** [comment]
For Q1, big_model.pt inference result is not equal with small_model.pt in bn1.

**Comment by xizi** [comment]
Q1 have solved.

**Comment by xizi** [comment]
这个模型转到onnx，再到TensorRT十分蛋疼

**Comment by qjy981010** [comment]
> Q1 have solved.

Hi, can you tell me how do you solve Q1? I'm facing the same problem.
