### ISSUE TITLE
About geometric median pruning (get_filter_similar function)

### ISSUE THREAD

**Issue by jefersonf** [he-y/filter-pruning-geometric-median#43]
As you said [here](https://github.com/he-y/filter-pruning-geometric-median/issues/19#issuecomment-513444709), even when you define a compress rate (e.g pruning rate) the total remaining filters are less than the actual compress rate.

 That said, 

- Why prune by geometric median after applying l2-norm? 
- Isn't similarity a good _proxy_ of the importance of the filter by itself?

**Comment by he-y** [comment]
Q1:
For the compatibility of PFGM-only and FPGM-mix.
![image](https://user-images.githubusercontent.com/10541284/69134542-98320600-0af2-11ea-9a25-89974ded5f35.png)

Q2:
If a layer has N filters. Then one filter has **N-1** distance with other filters.
Different to use these distances to measure importance.

**Comment by jefersonf** [comment]
Thanks for your response, but it isn't that clear to me. 
 
> Q1:
For the compatibility of PFGM-only and FPGM-mix

What it means? Isn't clear yet.

 In fact my question was if the distance from an arbitrary filter to the geometric median wasn't a good measure for filter importance by itself without need of combining it with l2-norm pruning.

The confusion comes from this specific paragraph: 

> To address the problems mentioned above, we propose a novel filter pruning approach, named Filter Pruning via Geometric Median (FPGM). Different from the previous methods which prune filters with relatively less contribution, FPGM chooses the filters with the most replaceable contribution. Specifically, we calculate the Geometric Median (GM) [8] of the filters within the same layer. According to the characteristics of GM, the filter(s) F near it can be represented by the remaining ones. Therefore, pruning those filters will not have substantial negative influences on model performance. **Note that FPGM does not utilize norm based criterion to select filters to prune, which means its performance will not deteriorate even when failing to meet requirements for norm-based criterion.**

**Comment by he-y** [comment]
Thanks for the clarification.
As shown in README.md, we have two parameters for the pruning rate.

> Note1: rate_norm = 0.9 means pruning 10% filters by norm-based criterion, rate_dist = 0.2 means pruning 20% filters by distance-based criterion.

So if we set rate_norm = 1, only the GM method would be activated. **This is so-called "FPGM-only".**
GM is a good measure, which is the main point of our paper.

The norm-based method here is for Section 4.4 of the paper. We want to see if GM can combine with norm-based method, which is called **"FPGM-mix".**:
![image](https://user-images.githubusercontent.com/10541284/69146627-316d1680-0b0b-11ea-9790-d02d0c17a3bb.png)
