### ISSUE TITLE
How to use the pruned small model directly?

### ISSUE THREAD

**Issue by SecondLi** [he-y/filter-pruning-geometric-median#44]
Hello,thank you for your code.
Now I want to use the pruned resnet model directly you released at https://github.com/he-y/soft-filter-pruning/releases/tag/ResNet50_pruned. I have checked get_small_model.py, and I found that when creating a small model, you provide index and bn_value, and these two are obtained from the big model,does this mean if I want to use the small model,I must have the big model to get the index and bn_value?

**Comment by he-y** [comment]
Thanks for your interest.
The bn_value is from the ''pruned model with zero'', which is called the big model. This one is different from the unpruned model.
Please take a look at the [soft filter pruning](https://github.com/he-y/soft-filter-pruning).
