### ISSUE TITLE
the pruning interval looks useless.

### ISSUE THREAD

**Issue by sseung0703** [he-y/filter-pruning-geometric-median#46]
your algorithms looks prune the network every end of a epoch. However, it is not.

If you prune P% weights. Norm criterion is disabled, because zero is the lowest.

Also, Distance criterion is disabled, because all of pruned weights's distance is zero.

I checked the pruned index of every end of epoch, and they are not changed.

Am I wrong?

**Comment by he-y** [comment]
You are right.
This operation is for the compatibility of soft filter pruning.
Please take a look at [this reply](https://github.com/he-y/filter-pruning-geometric-median/issues/39#issuecomment-544425734).

**Comment by sseung0703** [comment]
Ok, these things are for soft filter pruning. But why they are explained in your new paper?
Even, you put algorithm about it in paper.

**Comment by he-y** [comment]
Yes. 
FPGM is about pruning criteria, and soft filter pruning is about pruning mechanism.
The algorithm in this paper is for a general framework containing both mechanisms.

**Comment by he-y** [comment]
I am not quite sure about your question.
You want the pruned index filter change or not?
