### ISSUE TITLE
FLOPS Calculator has error.

### ISSUE THREAD

**Issue by sseung0703** [he-y/filter-pruning-geometric-median#49]
Your flops calculator has error.
Surely, number of filter is integer, but in your code, it is float.
In your pruning algorithm applying ceil to number of filter make it right.
After correct them, in case of resnet110-cifar10, 
40% pruning only reduce 40.26% FLOPS and
50% pruning only reduce 50.47% FLOPS.
I have to check it again, but I'm sure your one is wrong.

**Comment by he-y** [comment]
You are wrong.
The gap between the FLOPs from integer calculation and float calculation is small.
