### ISSUE TITLE
Question about pruning_cifar10.sh.

### ISSUE THREAD

**Issue by XiangqianMa** [he-y/filter-pruning-geometric-median#5]
When I read the `pruning_cifar10.sh` file,I found the following shell function:
```
run20_2(){
(pruning_pretrain_resnet20 0 /data/yahe/cifar_GM2/pretrain_0.01/cifar10_resnet20_ratenorm0.7_ratedist0.1_varience1 1 0.1)&
(pruning_pretrain_resnet20 0 /data/yahe/cifar_GM2/pretrain_0.01/cifar10_resnet20_ratenorm0.7_ratedist0.1_varience2 1 0.1)&
(pruning_pretrain_resnet20 0 /data/yahe/cifar_GM2/pretrain_0.01/cifar10_resnet20_ratenorm0.7_ratedist0.1_varience3 1 0.1)&


(pruning_scratch_resnet20 0 ./data/cifar_GM2/scratch/cifar10_resnet20_ratenorm0.7_ratedist0.1_varience1 1 0.1)&
(pruning_scratch_resnet20 0 ./data/cifar_GM2/scratch/cifar10_resnet20_ratenorm0.7_ratedist0.1_varience2 1 0.1)&
(pruning_scratch_resnet20 0 ./data/cifar_GM2/scratch/cifar10_resnet20_ratenorm0.7_ratedist0.1_varience3 1 0.1)&
}
```
I have some question about this function, why do you run three sub shells at the same time? I find the parameters of function `pruning_scratch_resnet20 ` in these three sub shells are same except the `save_path`. Can I just run one sub shell, such as the first one?
It would be appreciate if i could receive your reply! Thank you!

**Comment by he-y** [comment]
This is for calculating the variance of our method. 
Every commander will have a different random seed, and potentially a different result. 
For small dataset like CIFAR-10, it is necessary to run several times to validate the effectiveness of methods.

**Comment by XiangqianMa** [comment]
Thank for your reply!

**Comment by appleleaves** [comment]
Should the *ratenorm0.7_ratedist0.1* has an argument as 0.7 and 0.1 instead of 1 and 0.1?

**Comment by he-y** [comment]
Yes, corrected in [issue](https://github.com/he-y/filter-pruning-geometric-median/issues/26).
