### ISSUE TITLE
Figure 2. norm-based criterion.question

### ISSUE THREAD

**Issue by zihaozhang9** [he-y/filter-pruning-geometric-median#50]
Hello! I have a question. In Figure 2, Figure 2a, Small Norm Deviation, green is not good because the variance is small and the search space is small. Figure 2b, Large Minimum Norm, green is not good because v1 ′ ′ v1 → 0. I don't understand why the minimum value of the norm needs to be close to 0, and why is the blue one good?

**Comment by he-y** [comment]
Pruning a filter is similar to set the filter weight to **zero**.
Therefore, to reduce the effect of pruning, the ''small-norm-less-important'' assumption chooses the filter whose weights are near to zero, or, whose norm is near to zero.

**Comment by zihaozhang9** [comment]
ok, thank you very much;
There are still some questions.
Why is it not used in the training process, as in the paper "soft-filter-pruning", to keep the pruned nodes. [During training](https://github.com/he-y/filter-pruning-geometric-median/blob/master/pruning_cifar10.py#L313), the pruned filter is no longer updated.
During training, the weight set to 0 does not seem to be updated anymore. The log printed by the code "[m.if_zero ()](https://github.com/he-y/filter-pruning-geometric-median/blob/master/pruning_cifar10.py#L248)" shows that the number of 0 has not changed.

**Comment by he-y** [comment]
Please take a look at [this issue](https://github.com/he-y/filter-pruning-geometric-median/issues/9) for this question.
