### ISSUE TITLE
Maybe a Typo in pruning_cifar10.sh

### ISSUE THREAD

**Issue by appleleaves** [he-y/filter-pruning-geometric-median#51]
Thanks for sharing the codes.
In the scripts, the file pruning_cifar10.sh may have some typos.
As the save name is ratenorm0.7_ratedist0.1, the input for argument '--rate_norm' is 1.
Is it a mistake?
If not, I would need help to understand it.

**Comment by he-y** [comment]
Yes, this is a typo.
Thanks for pointing out.

**Comment by he-y** [comment]
The correct accuracy has been updated in [this issue](https://github.com/he-y/filter-pruning-geometric-median/issues/26).
