### ISSUE TITLE
关于论文baseline的学习率设置

### ISSUE THREAD

**Issue by ghost** [he-y/filter-pruning-geometric-median#52]
大佬，您的论文中的cifar10的reset 的baseline的学习率是60,120,160epoch设置为0.01，0.001,0.0001吗

**Comment by ghost** [comment]
还有wd是0.0001吗

**Comment by ghost** [comment]
还是学习率是60,120,160 epoch设置为0.02,0.004,0.0008，wd是0.0001

**Comment by he-y** [comment]
> 还是学习率是60,120,160 epoch设置为0.02,0.004,0.0008，wd是0.0001

this is right.
Please refer to this [code](https://github.com/he-y/filter-pruning-geometric-median/blob/master/scripts/pruning_cifar10_new.sh#L21-L22).

**Comment by ghost** [comment]
> > 还是学习率是60,120,160 epoch设置为0.02,0.004,0.0008，wd是0.0001
> 
> this is right.
> Please refer to this [code](https://github.com/he-y/filter-pruning-geometric-median/blob/master/scripts/pruning_cifar10_new.sh#L21-L22).

也就是说baseline的wd为0.0001，修剪的时候wd为0.0005.是这样理解吗？

**Comment by ghost** [comment]
如果学习率是60,120,160 epoch设置为0.02,0.004,0.0008，wd是0.0005训练的不修剪baseline准确率就会比论文中的的baseline高不少。如果学习率是60,120,160 epoch设置为0.02,0.004,0.0008，wd是0.0001训练的不修剪baseline准确率就会比论文中的的baseline低不少。

**Comment by he-y** [comment]
The baseline models are released at [this link](https://drive.google.com/drive/folders/1gbTTykmn6gk4IEug3jwDKFA5gDaNjowu).

**Comment by ghost** [comment]
> The baseline models are released at [this link](https://drive.google.com/drive/folders/1gbTTykmn6gk4IEug3jwDKFA5gDaNjowu).
了解了，3q
