### ISSUE TITLE
Finetune code and script

### ISSUE THREAD

**Issue by huangbiubiu** [he-y/filter-pruning-geometric-median#53]
It seems that there is no code or scripts for finetuning a pruned model by FPGM, how can I find them?

Thanks a lot for your great work!

**Comment by he-y** [comment]
Thanks for your interest.
The pruning and fine-tuning are in the same script file.

For example, [This line of code](https://github.com/he-y/filter-pruning-geometric-median/blob/master/scripts/pruning_cifar10.sh#L15) is the fine-tuning epoch.
