### ISSUE TITLE
Downsample mismatch 

### ISSUE THREAD

**Issue by zzqiuzz** [he-y/filter-pruning-geometric-median#54]
Hi! I've noticed that you implement downsample operation via
https://github.com/he-y/filter-pruning-geometric-median/blob/76f0ffefbdba7335251bfbafaadce49a2f08d2b9/models/res_utils.py#L4 which doubles the num of in-channel of shortcut. However,
![image](https://user-images.githubusercontent.com/24356886/72217303-69bb2f00-3567-11ea-9bb6-e79afcf49fbd.png)
 as shown above, the highlighted line implies an error. The shot above shows the topology of pruned Resnet20(on cifar10) using FPGM with a fixed pruning ratio 0.4, Downsampling this way doubles the num of in-channels of shortcut which is 40, while the num of out-channels of resudual is 39, thus dimension mismatch error will be encountered. 
In  terms of pruning on Resnet18(on imagenet),this error will be solved by https://github.com/he-y/filter-pruning-geometric-median/blob/76f0ffefbdba7335251bfbafaadce49a2f08d2b9/models/imagenet_resnet.py#L123 
so at the present  i'm not sure how to solve the mismatch problem on cifar10,and from this point , pruning by masks might be problematic.

**Comment by he-y** [comment]
Thanks for your interest.
Several different Downsample layers are provided in your mentioned files. 
Using [DownsampleC](https://github.com/he-y/filter-pruning-geometric-median/blob/76f0ffefbdba7335251bfbafaadce49a2f08d2b9/models/res_utils.py#L14) could solve the mismatch problem.
