### ISSUE TITLE
getting error when trying to load checkpoint

### ISSUE THREAD

**Issue by Allhailankurgupta** [he-y/filter-pruning-geometric-median#55]
I executed `!sh VGG_cifar/scripts/pruning_vgg_my_method.sh` the checkpoints were saved but when I wanted to load the checkpoints using
`torch.load('path-to-chkpt')`
to use the model I got this error
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-82efc73daf27> in <module>()
----> 1 torch.load('/content/logs/vgg_prune_precfg_varience4/model_best.pth.tar')

1 frames
/usr/local/lib/python3.6/dist-packages/torch/serialization.py in load(f, map_location, pickle_module)
    265         f = open(f, 'rb')
    266     try:
--> 267         return _load(f, map_location, pickle_module)
    268     finally:
    269         if new_fd:

/usr/local/lib/python3.6/dist-packages/torch/serialization.py in _load(f, map_location, pickle_module)
    418     unpickler = pickle_module.Unpickler(f)
    419     unpickler.persistent_load = persistent_load
--> 420     result = unpickler.load()
    421 
    422     deserialized_storage_keys = pickle_module.load(f)

AttributeError: Can't get attribute '_rebuild_tensor_v2' on <module 'torch._utils' from '/usr/local/lib/python3.6/dist-packages/torch/_utils.py'>
```

**Comment by Allhailankurgupta** [comment]
Also Can you please explain what do you mean by pruning from scratch?
1) -> is it training scratch model ( 100 epochs ) and then pruning and then training model ( 100 epochs ).
OR
2) ->is it training scratch model ( 1 epoch ) from and then pruning and then training model ( 1 epoch ) and repeating it.

if it is case 2 then I am not able to understand when you get the pruned model then when you will again prune it then more number of parameters will be pruned but accuracy will be less.
I mean it will not be able to gain accuracy as it is being pruned repetitively.

**Comment by he-y** [comment]
> Also Can you please explain what do you mean by pruning from scratch?
> 
> 1. -> is it training scratch model ( 100 epochs ) and then pruning and then training model ( 100 epochs ).
>    OR
> 2. ->is it training scratch model ( 1 epoch ) from and then pruning and then training model ( 1 epoch ) and repeating it.
> 
> if it is case 2 then I am not able to understand when you get the pruned model then when you will again prune it then more number of parameters will be pruned but accuracy will be less.
> I mean it will not be able to gain accuracy as it is being pruned repetitively.

Not 1 or 2.
Pruning the scratch model means:
1. scratch model without training
2. pruning it
3. retraining it for needed epochs.

We only prune once and retrain once.

**Comment by he-y** [comment]
For the first question, what's your PyTorch version?

**Comment by Allhailankurgupta** [comment]
I am using the same version as given 0.3.1.
I used colab though there were compatibility issues with torchvision.

-> Also in the code you are sorting on the basis of which points are least distant to other points. On the basis of the geometric median criteria.(get_similar_mask)
-> But in the paper and in the presentation on youtube it it given that first you find the geo_median then you find filters nearest to geo_median and remove from those fillers.
-> Could you please clarify.

**Comment by he-y** [comment]
Please take a look at Sec. 3.4 of [our paper](https://arxiv.org/pdf/1811.00250.pdf) which explains why we do not calculate the GM directly.

![image](https://user-images.githubusercontent.com/10541284/78418591-4a74ff00-7689-11ea-8379-ac851a0f642b.png)

**Comment by Allhailankurgupta** [comment]
Ok can you help regarding loading of models

**Comment by he-y** [comment]
[this discussion](https://discuss.pytorch.org/t/on-a-cpu-device-how-to-load-checkpoint-saved-on-gpu-device/349) might help.

**Comment by Allhailankurgupta** [comment]
You have used pytorch 0.3.1 and torchvision 0.3 but when i installed both of them in colab, it gave  message that torchvision 0.3 is not compatible with pytorch 0.3.1

**Comment by he-y** [comment]
torchvision version is 0.2 not 0.3.
Sorry for the mistake.
