### ISSUE TITLE
Some questions about cal_flop.py

### ISSUE THREAD

**Issue by lgzz** [he-y/filter-pruning-geometric-median#57]
Why do the first layer and second layer not the same? Both of the output and input channel of the first layer are reduced, too.
if index % 2 != 0:
     # first layer of block, only output channal reduced, input channel remain the same
          flop += channel[0] * width[0] * width[0] * 9 * channel[0] * (prune_rate)
     elif index % 2 == 0:
     # second layer of block, both input and output channal reduced
          flop += channel[0] * width[0] * width[0] * 9 * channel[0] * (prune_rate ** 2)

**Comment by lgzz** [comment]
By the way, you didn't calculate the flops in linear layer, right?

**Comment by he-y** [comment]
The last layer of block should consider the effect of shortcut, so the output channel remains the same and does not reduce.
Yes, FC only contributes little so it is not considered.

**Comment by lgzz** [comment]
But in the code, both input and output channal of the second layer reduced.
If we don't prune the input channel of the first layer, the output channel of the second layer should not be reduced, then the code should be flop += channel[0] * width[0] * width[0] * 9 * channel[0] * (prune_rate)
If we prune the input channel of the first layer, the output channel of the second layer should be reduced, too, then the code should be flop += channel[0] * width[0] * width[0] * 9 * channel[0] * (prune_rate ** 2)
But your code confuse the two situations, I don't know whether you have pruned the input channel of the first layer or not.

**Comment by he-y** [comment]
[This link](https://github.com/he-y/filter-pruning-geometric-median/issues/23#issuecomment-518118162) is about the comparison of the original and pruned model.
Does this help?

**Comment by lgzz** [comment]
Assume the original block is:
BasicBlock(
      (conv1): Conv2d(16, 16)
      (conv2): Conv2d(16, 16)
)
If we set the prune ratio 0.5.
I just want to know whether the pruned block is:
BasicBlock(
      (conv1): Conv2d(16, 8)
      (conv2): Conv2d(8, 16)
)
or:
BasicBlock(
      (conv1): Conv2d(8, 8)
      (conv2): Conv2d(8, 8)
)

**Comment by he-y** [comment]
BasicBlock(
(conv1): Conv2d(16, 8)
(conv2): Conv2d(8, 8)
)

**Comment by lgzz** [comment]
But how to add the 16 input channels and 8 output channels up?

**Comment by he-y** [comment]
Please take a look at [this reply](https://github.com/he-y/filter-pruning-geometric-median/issues/38#issuecomment-543044443).
