### ISSUE TITLE
Pruning result on ResNet-18 of Imagenet

### ISSUE THREAD

**Issue by PkuDavidGuan** [he-y/filter-pruning-geometric-median#58]
Dear He,
      I hope to see the pruning results of ResNet-18 of ImageNet (the number of reserved channels) in the original paper. I checked the log on the google drive and  didn't find it. Could you help to provide it ?

**Comment by he-y** [comment]
Please take a look at [the file about ResNet-18](https://drive.google.com/drive/u/1/folders/1M83Y7yNj9mMq7etQLiGGElkNNEcOUW-6).
Other depths could be find at [this link](https://drive.google.com/drive/u/1/folders/1DOYiOZGQxr94rWsEw73ezz9a-0hcNf-2).
