### ISSUE TITLE
Reproduction of ResNet-18 from scratch

### ISSUE THREAD

**Issue by zzqiuzz** [he-y/filter-pruning-geometric-median#6]
Hi! After run 'python pruning_imagenet.py -a resnet18  --save_dir ./snapshots/resnet18-rate-0.7 --rate_norm 1 --rate_dist 0.3 --layer_begin 0 --layer_end 57 --layer_inter 3  /home/share/data/ilsvrc12_shrt_256_torch/' with 4 GPUs，batchsize=256

The **result** got  Prec@1 66.662 Prec@5 87.440 Error@1 33.338 which has a little drop as yours in Top-1 @67.78 Top-5 @88.01 
How & how

**Comment by he-y** [comment]
Please find the pre-trained ResNet18 [here](https://drive.google.com/drive/u/1/folders/1M83Y7yNj9mMq7etQLiGGElkNNEcOUW-6).
Full models [here](https://drive.google.com/drive/u/1/folders/1w_Max8L5ICJZSrlha8UybHfICik-iX95).
We use 1 GPU to train ResNet18.
