### ISSUE TITLE
Problems on the implementation

### ISSUE THREAD

**Issue by pyt1234** [he-y/filter-pruning-geometric-median#61]
@he-y I was wondering how did you prune the last conv in the residual block but not prune the downsample conv? how did you make the summation?  For example:

> name of layer: layer1.0.conv3.weight
> *** small model torch.Size([180, 45, 1, 1])
> *** big model torch.Size([256, 64, 1, 1])
> name of layer: layer1.0.bn3.weight
> *** small model torch.Size([180])
> *** big model torch.Size([256])
> name of layer: layer1.0.bn3.bias
> *** small model torch.Size([180])
> *** big model torch.Size([256])
> name of layer: layer1.0.downsample.0.weight
> *** small model torch.Size([256, 45, 1, 1])
> *** big model torch.Size([256, 64, 1, 1])
> name of layer: layer1.0.downsample.1.weight
> *** small model torch.Size([256])
> *** big model torch.Size([256])
> name of layer: layer1.0.downsample.1.bias
> *** small model torch.Size([256])
> *** big model torch.Size([256])

180 vs 256 channels? Also, ref #38

in https://github.com/he-y/filter-pruning-geometric-median/issues/23#issuecomment-645203431_

**Comment by he-y** [comment]
![image](https://user-images.githubusercontent.com/10541284/84872721-96024b00-b0c5-11ea-9e74-1ec8b0d77813.png)
