### ISSUE TITLE
about training time

### ISSUE THREAD

**Issue by wangguanan** [he-y/filter-pruning-geometric-median#62]
Hi, thanks for your awesome work.
will the pruning operation slow down the training stage?
if yes, could you please show a quantitative result. 
for example, training res50 on imagenet becomes slow from xxx hours to xxx hours.

**Comment by he-y** [comment]
Thanks for your interest.
The pruning operation would NOT slow down the training stage.

A sanity check: 
training a ResNet on CIFAR takes about 20 hours, the pruning operation would finish within several seconds.

**Comment by wangguanan** [comment]
that is exciting!
how long it will take to train a ResNet50 on ImageNet?

**Comment by he-y** [comment]
That depends on the GPU.
On V100, it takes about 3-4 days to train a ResNet50 on ImageNet from scratch.

**Comment by wangguanan** [comment]
thanks
