### ISSUE TITLE
Confusion with init_rate

### ISSUE THREAD

**Issue by hzx829** [he-y/filter-pruning-geometric-median#66]
https://github.com/he-y/filter-pruning-geometric-median/blob/76f0ffefbdba7335251bfbafaadce49a2f08d2b9/pruning_cifar10.py#L568
Does this code means to prune all the layer by distance out of range(args.layer_begin, args.layer_end + 1, args.layer_inter)?
If so, I think self.distance_rate[index] should be 0, because you don't want to prune anything out of range(args.layer_begin, args.layer_end + 1, args.layer_inter), right?

**Comment by he-y** [comment]
Sorry for the unclear code.
This line is not necessary and would not be active.
The following pruning operations are conducted on the layers within the range(args.layer_begin, args.layer_end + 1, args.layer_inter).
