### ISSUE TITLE
Pruning filters and channels

### ISSUE THREAD

**Issue by zzqiuzz** [he-y/filter-pruning-geometric-median#7]
Hi! I have a puzzle that if you prune some filters in a specific layer, consequently you also need to prune channels in the next layer accordingly.But your codes just zerorize filters for each layer instead of considering the ordered relationship between two layers i.e. remove both filters in the ith layer and channels in the i+1th layer.  Especially when the pruning process ends, if all targeted filters are pruned in the whole network, Error will be occured in the inference process, cause the reason overhead.

**Comment by he-y** [comment]
Please refer to the issue of my other repo: [link](https://github.com/he-y/soft-filter-pruning/issues/11).
The issue is about to delete zeros.
I will update the code in this repo shortly.

**Comment by zzqiuzz** [comment]
oh got it. Filters pruned in the previous layer generate zero featuremaps in the next layer,thus there's no impact pruning the relative channels in the filters of next layer. 3ks

**Comment by liuwenran** [comment]
But when it comes to resnet block,  the input channel number of residual part is equal to the shortcut part, after conv pruned in the residual part, the output channel number of residual part becomes fewer, so do we need to add conv layer to shortcut of resnet block like the method used in paper "PRUNING FILTERS FOR EFFICIENT CONVNETS"?
