### ISSUE TITLE
您好！请问get_small_model.py文件如何使用？谢谢！

### ISSUE THREAD

**Issue by topsail520** [he-y/filter-pruning-geometric-median#77]
您好！在这个文件中，我没有看到剪枝后含0的权重文件的加载代码。我参考脚本文件设置了参数后，就出现check_channel 首行代码报错：tuple index out of range，我没有找到原因。希望您能回答我的疑问，谢谢！祝身体健康！

**Comment by he-y** [comment]
Hi, please see [updates here](https://github.com/he-y/filter-pruning-geometric-median#whats-new) to use FPGM in pytorch and NNI.
