### ISSUE TITLE
FPGM on object detection model & implementation of NNI

### ISSUE THREAD

**Issue by gkrisp98** [he-y/filter-pruning-geometric-median#78]
Hi, is it possible to apply FPGM pruning on a object detection model ? And are the changes easy and straightforward to make ?

Also, I see that the implementation of NNI uses L2 norm to calculate importance scores of filters. Is this implementation correct and safe to use ?

**Comment by he-y** [comment]
Hi, please see [updates here](https://github.com/he-y/filter-pruning-geometric-median#whats-new) to use FPGM in pytorch and NNI.
