### ISSUE TITLE
Abour similar_small_index

### ISSUE THREAD

**Issue by zhongshaoyy** [he-y/filter-pruning-geometric-median#8]
When running the code, I found that the similar_small_index always includes indexes from 0 to n,such as [0,1,2,3,4,5,6,7,8] .And  the similar_sum matrix always  has some equal numbers in the matrix.  Is this because there are some setttings to constrain the matrix?

**Comment by yyx1107** [comment]
similar_pruned_num = int(weight_torch.size()[0] * distance_rate)
...
similar_small_index = similar_sum.argsort()[:  similar_pruned_num]
The distance_rate is an invariant constant, so the num of filters that should be pruned each layer is also invariant.Or  you can add me QQ 1017176539 .Maybe I can help you with the issue.

**Comment by he-y** [comment]
Please read the [code](https://github.com/he-y/filter-pruning-geometric-median/blob/master/pruning_imagenet.py#L52-L53) to find the definition of these parameters.

These pruning rates are pre-defined. Please read section 4.1. Experimental Settings of our paper for details.
